<?php
/**
 * Drand quicknet HTTP client.
 *
 * Randomness is generated by the League of Entropy's drand network and
 * served over multiple independent public relays. The primary relay is
 * Cloudflare's (https://drand.cloudflare.com). This client:
 *
 *  - computes round numbers from the chain's public genesis/period,
 *  - fetches beacons with automatic relay fallback,
 *  - optionally cross-checks the beacon against a second independent relay,
 *  - always verifies locally that randomness == sha256(signature), which is
 *    how quicknet derives randomness from the BLS threshold signature.
 *
 * @package The_RNG
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class TRNG_Drand {

	/**
	 * Round number in effect at a given unix time.
	 *
	 * @param int|null $time Unix timestamp (defaults to now).
	 * @return int
	 */
	public static function current_round( $time = null ) {
		$time = ( null === $time ) ? time() : (int) $time;
		if ( $time < TRNG_CHAIN_GENESIS ) {
			return 1;
		}
		return (int) floor( ( $time - TRNG_CHAIN_GENESIS ) / TRNG_CHAIN_PERIOD ) + 1;
	}

	/**
	 * Unix time at which a round is emitted.
	 *
	 * @param int $round Round number.
	 * @return int
	 */
	public static function time_of_round( $round ) {
		return TRNG_CHAIN_GENESIS + ( ( (int) $round - 1 ) * TRNG_CHAIN_PERIOD );
	}

	/**
	 * Configured relay list (sanitised).
	 *
	 * @return string[]
	 */
	public static function relays() {
		$relays = TRNG_Settings::get( 'relays' );
		if ( ! is_array( $relays ) || empty( $relays ) ) {
			$relays = TRNG_Settings::defaults()['relays'];
		}
		return array_values( array_filter( array_map( 'esc_url_raw', $relays ) ) );
	}

	/**
	 * Fetch a beacon from one relay.
	 *
	 * @param string     $relay Relay base URL.
	 * @param int|string $round Round number or 'latest'.
	 * @return array|WP_Error Beacon array {round, signature, randomness}.
	 */
	protected static function fetch_from( $relay, $round ) {
		$url = rtrim( $relay, '/' ) . '/' . TRNG_CHAIN_HASH . '/public/' . $round;

		$response = wp_remote_get(
			$url,
			array(
				'timeout'   => 8,
				'sslverify' => true,
				'headers'   => array( 'Accept' => 'application/json' ),
			)
		);

		if ( is_wp_error( $response ) ) {
			return $response;
		}

		$code = wp_remote_retrieve_response_code( $response );
		if ( 200 !== (int) $code ) {
			return new WP_Error( 'trng_http_' . $code, sprintf( 'Relay %s returned HTTP %d.', $relay, $code ) );
		}

		$body = json_decode( wp_remote_retrieve_body( $response ), true );
		if ( ! is_array( $body ) || ! isset( $body['round'], $body['signature'], $body['randomness'] ) ) {
			return new WP_Error( 'trng_bad_body', sprintf( 'Relay %s returned an unexpected payload.', $relay ) );
		}

		// Local integrity check: quicknet randomness = sha256(signature bytes).
		$sig_bin = @hex2bin( $body['signature'] );
		if ( false === $sig_bin || ! hash_equals( hash( 'sha256', $sig_bin ), strtolower( $body['randomness'] ) ) ) {
			return new WP_Error( 'trng_bad_randomness', sprintf( 'Relay %s beacon failed the sha256(signature) check.', $relay ) );
		}

		return array(
			'round'      => (int) $body['round'],
			'signature'  => strtolower( $body['signature'] ),
			'randomness' => strtolower( $body['randomness'] ),
			'relay'      => $relay,
		);
	}

	/**
	 * Fetch a beacon with relay fallback + optional independent cross-check.
	 *
	 * @param int|string $round Round number or 'latest'.
	 * @return array|WP_Error Beacon plus 'endpoints_used' listing agreeing relays.
	 */
	public static function get_beacon( $round = 'latest' ) {
		$relays  = self::relays();
		$beacon  = null;
		$used    = array();
		$errors  = array();

		foreach ( $relays as $relay ) {
			$result = self::fetch_from( $relay, $round );
			if ( is_wp_error( $result ) ) {
				$errors[] = $result->get_error_message();
				continue;
			}
			$beacon = $result;
			$used[] = $relay;
			break;
		}

		if ( null === $beacon ) {
			return new WP_Error( 'trng_all_relays_failed', 'No drand relay could be reached: ' . implode( ' | ', $errors ) );
		}

		// Cross-check against a second, different relay when configured.
		if ( TRNG_Settings::get( 'cross_check' ) && 'latest' !== $round ) {
			foreach ( $relays as $relay ) {
				if ( $relay === $beacon['relay'] ) {
					continue;
				}
				$second = self::fetch_from( $relay, $round );
				if ( is_wp_error( $second ) ) {
					continue;
				}
				if ( ! hash_equals( $beacon['signature'], $second['signature'] ) ) {
					return new WP_Error( 'trng_relay_mismatch', 'Independent relays disagree on the beacon — draw aborted for safety.' );
				}
				$used[] = $relay;
				break;
			}
		}

		$beacon['endpoints_used'] = implode( ',', $used );
		return $beacon;
	}

	/**
	 * Latest round number, preferring the relay's answer with a local
	 * time-based fallback so the generator still works if relays are
	 * briefly unreachable at commit time.
	 *
	 * @return int
	 */
	public static function latest_round() {
		$beacon = self::get_beacon( 'latest' );
		if ( ! is_wp_error( $beacon ) ) {
			return (int) $beacon['round'];
		}
		return self::current_round();
	}
}
